import React from 'react';
import type { Inspection } from '../../types';
import { Layers, Activity, Thermometer, Gauge, Server, WifiOff } from 'lucide-react';
import { DemoBanner } from '../common/DemoBanner';

interface ProductionContextCardProps {
  inspection: Inspection;
}

export const ProductionContextCard: React.FC<ProductionContextCardProps> = ({ inspection }) => {
  const p = inspection.parameters || {
    temperature: 72.0,
    vibration: 4.8,
    pressure: 6.2,
    speed: 1480,
    envTemp: 29.0,
    envHumidity: 68.0
  };

  const isOffline = inspection.factory_status === 'Virtual Factory Offline' || inspection.factory_source_label === 'OFFLINE';
  const sourceLabel = inspection.factory_source_label || (isOffline ? 'Virtual Factory Offline' : 'SIMULATED FACTORY DATA');

  return (
    <div className="scada-card">
      <div className="scada-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Layers className="w-4 h-4 text-system-blue" />
          <span className="scada-title">LAPTOP 2 — VIRTUAL FACTORY PRODUCTION CONTEXT</span>
        </div>
        <span
          style={{
            fontSize: '0.7rem',
            padding: '0.2rem 0.6rem',
            backgroundColor: isOffline ? '#2C1B1F' : 'rgba(79, 124, 172, 0.15)',
            border: `1px solid ${isOffline ? '#D9383A' : '#4F7CAC'}`,
            borderRadius: '4px',
            color: isOffline ? '#F87171' : '#4F7CAC',
            fontWeight: 700,
            display: 'inline-flex',
            alignItems: 'center',
            gap: '0.3rem'
          }}
        >
          {isOffline ? <WifiOff size={12} /> : <Server size={12} />}
          {sourceLabel}
        </span>
      </div>

      <div style={{ marginBottom: '1rem' }}>
        <DemoBanner message={isOffline ? "VIRTUAL FACTORY OFFLINE — Laptop 2 process simulator not reachable." : "SIMULATED FACTORY DATA — Telemetry generated by Laptop 2 Virtual Factory Simulator"} />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '0.75rem', marginBottom: '1rem' }}>
        <div style={{ backgroundColor: '#162235', padding: '0.6rem 0.75rem', borderRadius: '4px', border: '1px solid #26364A' }}>
          <span className="scada-label">MACHINE STATION</span>
          <span style={{ fontSize: '1rem', fontWeight: 700, color: '#E8EDF3', fontFamily: 'var(--font-mono)' }}>
            {inspection.machineId || inspection.machine_id || 'M03'}
          </span>
        </div>

        <div style={{ backgroundColor: '#162235', padding: '0.6rem 0.75rem', borderRadius: '4px', border: '1px solid #26364A' }}>
          <span className="scada-label">PRODUCTION BATCH</span>
          <span style={{ fontSize: '1rem', fontWeight: 700, color: '#4F7CAC', fontFamily: 'var(--font-mono)' }}>
            {inspection.batchId || inspection.batch_id || 'B1042'}
          </span>
        </div>

        <div style={{ backgroundColor: '#162235', padding: '0.6rem 0.75rem', borderRadius: '4px', border: '1px solid #26364A' }}>
          <span className="scada-label">OPERATOR SHIFT</span>
          <span style={{ fontSize: '1rem', fontWeight: 700, color: '#E8EDF3', fontFamily: 'var(--font-mono)' }}>
            {inspection.shift || inspection.shift_id || 'Shift B'}
          </span>
        </div>

        <div style={{ backgroundColor: '#162235', padding: '0.6rem 0.75rem', borderRadius: '4px', border: '1px solid #26364A' }}>
          <span className="scada-label">PRODUCT SKU</span>
          <span style={{ fontSize: '0.9rem', fontWeight: 600, color: '#8D9AAA', fontFamily: 'var(--font-mono)' }}>
            {inspection.productId || inspection.product_id || 'RING-001'}
          </span>
        </div>
      </div>

      {/* Sensor Telemetry Readings */}
      <span className="scada-label" style={{ marginBottom: '0.5rem', display: 'block' }}>
        SIMULATED FACTORY DATA (LAPTOP 2 PROCESS READINGS)
      </span>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.75rem' }}>
        {/* Temperature */}
        <div
          style={{
            backgroundColor: p.temperature > 70 ? 'rgba(217, 154, 43, 0.1)' : '#162235',
            border: `1px solid ${p.temperature > 70 ? '#D99A2B' : '#26364A'}`,
            padding: '0.65rem 0.8rem',
            borderRadius: '4px'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: '#8D9AAA', fontSize: '0.75rem' }}>
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
              <Thermometer size={14} style={{ color: p.temperature > 70 ? '#D99A2B' : '#4F7CAC' }} />
              MACHINE TEMP
            </span>
            {p.temperature > 70 && <span style={{ color: '#D99A2B', fontWeight: 600 }}>ELEVATED</span>}
          </div>
          <span style={{ fontSize: '1.25rem', fontWeight: 700, fontFamily: 'var(--font-mono)', color: p.temperature > 70 ? '#D99A2B' : '#E8EDF3' }}>
            {p.temperature.toFixed(1)}°C
          </span>
        </div>

        {/* Vibration */}
        <div
          style={{
            backgroundColor: p.vibration > 3.0 ? 'rgba(229, 83, 83, 0.12)' : '#162235',
            border: `1px solid ${p.vibration > 3.0 ? '#E55353' : '#26364A'}`,
            padding: '0.65rem 0.8rem',
            borderRadius: '4px'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: '#8D9AAA', fontSize: '0.75rem' }}>
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
              <Activity size={14} style={{ color: p.vibration > 3.0 ? '#E55353' : '#4F7CAC' }} />
              VIBRATION
            </span>
            {p.vibration > 3.0 && <span style={{ color: '#E55353', fontWeight: 600 }}>ANOMALY</span>}
          </div>
          <span style={{ fontSize: '1.25rem', fontWeight: 700, fontFamily: 'var(--font-mono)', color: p.vibration > 3.0 ? '#E55353' : '#E8EDF3' }}>
            {p.vibration.toFixed(1)} mm/s
          </span>
        </div>

        {/* Pressure */}
        <div style={{ backgroundColor: '#162235', border: '1px solid #26364A', padding: '0.65rem 0.8rem', borderRadius: '4px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', color: '#8D9AAA', fontSize: '0.75rem' }}>
            <Gauge size={14} style={{ color: '#4F7CAC' }} />
            PRESSURE
          </div>
          <span style={{ fontSize: '1.25rem', fontWeight: 700, fontFamily: 'var(--font-mono)', color: '#E8EDF3' }}>
            {p.pressure.toFixed(1)} bar
          </span>
        </div>

        {/* Speed */}
        <div style={{ backgroundColor: '#162235', border: '1px solid #26364A', padding: '0.65rem 0.8rem', borderRadius: '4px' }}>
          <span className="scada-label">MACHINE SPEED</span>
          <span style={{ fontSize: '1.1rem', fontWeight: 700, fontFamily: 'var(--font-mono)', color: '#E8EDF3' }}>
            {p.speed} RPM
          </span>
        </div>

        {/* Env Temp */}
        <div style={{ backgroundColor: '#162235', border: '1px solid #26364A', padding: '0.65rem 0.8rem', borderRadius: '4px' }}>
          <span className="scada-label">ENVIRONMENT TEMP</span>
          <span style={{ fontSize: '1.1rem', fontWeight: 700, fontFamily: 'var(--font-mono)', color: '#E8EDF3' }}>
            {(p.envTemp || 29.0).toFixed(1)}°C
          </span>
        </div>

        {/* Env Humidity */}
        <div style={{ backgroundColor: '#162235', border: '1px solid #26364A', padding: '0.65rem 0.8rem', borderRadius: '4px' }}>
          <span className="scada-label">HUMIDITY</span>
          <span style={{ fontSize: '1.1rem', fontWeight: 700, fontFamily: 'var(--font-mono)', color: '#E8EDF3' }}>
            {p.envHumidity || 68}%
          </span>
        </div>
      </div>
    </div>
  );
};
